name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate composer.json
        run: composer validate

  php-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.0
          - 8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - name: PHP lint
        run: "find *.php Classes Configuration -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.0
          - 8.1
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies with expected TYPO3 version
        run: composer require --prefer-dist --no-progress

      - name: Code Quality (by PHPStan)
        run: ./vendor/bin/phpstan analyse
